version: '2'
services:
    restjwtdemo-app:
        image: restjwtdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://restjwtdemo-mysql:3306/restjwtdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    restjwtdemo-mysql:
        extends:
            file: mysql.yml
            service: restjwtdemo-mysql
